server:
  servlet:
    context-path: /ems_vue
  port: 8989

spring:
  application:
    name: ems
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/emp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity

logging:
  level:
    com.baizhi.dao: debug
    com.baizhi.service: info
    com.baizhi.controller: info
